SET(LIBGP_SRC
  src/cov.cc
  src/cov_factory.cc
  src/cov_linear_ard.cc
  src/cov_linear_one.cc
  src/cov_matern3_iso.cc
  src/cov_matern5_iso.cc
  src/cov_noise.cc
  src/cov_rq_iso.cc
  src/cov_periodic_matern3_iso.cc
  src/cov_periodic.cc
  src/cov_se_ard.cc
  src/cov_se_iso.cc
  src/cov_sum.cc
  src/cov_prod.cc
  src/abstract_gp.cc
  src/gp.cc
  src/basis_functions/bf_multi_scale.cc
  src/basis_functions/bf_solin.cc
  src/basis_functions/bf_fic.cc
  src/basis_functions/bf_fic_fixed.cc
  src/basis_functions/basisf_factory.cc
  src/gp_fic.cc
  src/gp_fic_optimized.cc
  src/gp_multiscale_optimized.cc
  src/gp_deg.cc
  src/gp_solin.cc
  src/gp_utils.cc
  src/sampleset.cc
  src/rprop.cc
  src/input_dim_filter.cc
  src/cg.cc
)

SET(LIBGP_INTERFACES 
  include/cov.h
  include/cov_factory.h
  include/cov_linear_ard.h
  include/cov_linear_one.h
  include/cov_matern3_iso.h
  include/cov_matern5_iso.h
  include/cov_noise.h
  include/cov_rq_iso.h
  include/cov_periodic_matern3_iso.h
  include/cov_periodic.h
  include/cov_se_ard.h
  include/cov_se_iso.h
  include/cov_sum.h
  include/cov_prod.h
  include/abstract_gp.h
  include/gp.h
  include/basis_functions/IBasisFunction.h
  include/basis_functions/bf_multi_scale.h
  include/basis_functions/bf_solin.h
  include/basis_functions/bf_fic.h
  include/basis_functions/bf_fic_fixed.h
  include/basis_functions/basisf_factory.h
  include/gp_fic.h
  include/gp_fic_optimized.h
  include/gp_multiscale_optimized.h
  include/gp_deg.h
  include/gp_solin.h
  include/gp_utils.h
  include/sampleset.h
  include/rprop.h
  include/input_dim_filter.h
  include/cg.h
)

SET(FAST_FOOD_SRC
  src/basis_functions/bf_fast_food.cc
)

SET(FAST_FOOD_INTERFACES
  include/basis_functions/bf_fast_food.h
)
